In [1]:
import pandas as pd
import numpy as np
data=pd.read_csv("zoo_data.csv")
data

,animal_name,hair,feathers,eggs,milk,airborne,aquatic,predator,toothed,backbone,breathes,venomous,fins,legs,tail,domestic,catsize,class_type
0,aardvark,1,0,0,1,0,0,1,1,1,1,0,0,4,0,0,1,1
1,antelope,1,0,0,1,0,0,0,1,1,1,0,0,4,1,0,1,1
2,bass,0,0,1,0,0,1,1,1,1,0,0,1,0,1,0,0,4
3,bear,1,0,0,1,0,0,1,1,1,1,0,0,4,0,0,1,1
4,boar,1,0,0,1,0,0,1,1,1,1,0,0,4,1,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,wallaby,1,0,0,1,0,0,0,1,1,1,0,0,2,1,0,1,1
97,wasp,1,0,1,0,1,0,0,0,0,1,1,0,6,0,0,0,6
98,wolf,1,0,0,1,0,0,1,1,1,1,0,0,4,1,0,1,1
99,worm,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,7
100,wren,0,1,1,0,1,0,0,0,1,1,0,0,2,1,0,0,2

In [3]:
x1=data['hair'].values
x2=data['feathers'].values
x3=data['eggs'].values
x4=data['milk'].values
x5=data['airborne'].values
x6=data['aquatic'].values
x7=data['predator'].values
x8=data['toothed'].values
x9=data['backbone'].values
x10=data['breathes'].values
x11=data['venomous'].values
x12=data['fins'].values
x13=data['legs'].values
x14=data['tail'].values
x15=data['domestic'].values
x16=data['catsize'].values
y =data['class_type'].values


X = np.array(list(zip(x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15,x16)))
X

Y=y
Y

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.25)


from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
from sklearn import tree

decision = tree.DecisionTreeClassifier(criterion='gini')
decision.fit(X_train,y_train)

y_predict=decision.predict(X_test)
y_score = accuracy_score(y_test,y_predict)
print('Accuracy: ', y_score)
y_test

print(classification_report(y_test,y_predict))

print(confusion_matrix(y_test,y_predict))

Accuracy:  0.9230769230769231
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        12
           2       1.00      1.00      1.00         6
           3       0.00      0.00      0.00         1
           4       1.00      1.00      1.00         2
           5       1.00      1.00      1.00         1
           6       0.50      0.50      0.50         2
           7       0.67      1.00      0.80         2

    accuracy                           0.92        26
   macro avg       0.74      0.79      0.76        26
weighted avg       0.90      0.92      0.91        26

[[12  0  0  0  0  0  0]
 [ 0  6  0  0  0  0  0]
 [ 0  0  0  0  0  1  0]
 [ 0  0  0  2  0  0  0]
 [ 0  0  0  0  1  0  0]
 [ 0  0  0  0  0  1  1]
 [ 0  0  0  0  0  0  2]]

/home/dslab/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))